FROM apache/airflow:2.7.3-python3.10

USER airflow

# Install additional Python modules
RUN pip install --upgrade pip
COPY ./requirements_af.txt .
RUN pip3 install -r requirements_af.txt

USER airflow