CREATE TABLE dermDF (
    erythema INT,
    scaling INT,
    definite_borders INT,
    itching INT,
    koebner_phenomenon INT,
    polygonal_papules INT,
    follicular_papules INT,
    oral_mucosal_involvement INT,
    knee_and_elbow_involvement INT,
    scalp_involvement INT,
    family_history INT,
    melanin_incontinence INT,
    eosinophils_infiltrate INT,
    PNL_infiltrate INT,
    fibrosis_papillary_dermis INT,
    exocytosis INT,
    acanthosis INT,
    hyperkeratosis INT,
    parakeratosis INT,
    clubbing_rete_ridges INT,
    elongation_rete_ridges INT,
    thinning_suprapapillary_epidermis INT,
    spongiform_pustule INT,
    munro_microabcess INT,
    focal_hypergranulosis INT,
    disappearance_granular_layer INT,
    vacuolisation_damage_basal_layer INT,
    spongiosis INT,
    saw_tooth_appearance_retes INT,
    follicular_horn_plug INT,
    perifollicular_parakeratosis INT,
    inflammatory_mononuclear_infiltrate INT,
    band_like_infiltrate INT,
    age VARCHAR,
    class INT
);

UPDATE dermDF
SET age = NULLIF(age, '?');